import 'package:flutter/material.dart' ;

class Book {

  String title = "Principles of Product Design" ;
  String author = "Aaron Walter" ;
  Color color = Colors.blue[900] ;
  Color baseColor = Colors.blue ;
  String imageAsset = "assets/books3.jpg" ;
  String bookText = "Successful design-driven companies building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design Successful design-driven companies"
      " building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design Successful design-driven companies"
      " building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design Successful design-driven companies building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design Successful design-driven companies"
      " building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design Successful design-driven companies"
      " building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design Successful design-driven companies building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design Successful design-driven companies"
      " building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design Successful design-driven companies"
      " building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design Successful design-driven companies building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design Successful design-driven companies"
      " building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design Successful design-driven companies"
      " building the best"
      " products with the strongest design teams have practices in common. "
      "These extensively researched core best practices will help your team "
      "design better, faster, and more collaboratively. Combined with the"
      " power of design thinking, these product design principles will "
      "accelerate your team's design" ;

}